name: supply_chain
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.1
  - tqdm>=4.65.0
  - pip>=23.0.1
  - pip:
    - tensorflow-macos>=2.14.0
    - tensorflow-metal>=1.0.0
    - scikit-fuzzy>=0.4.2
    - typing-extensions>=4.10.0
    - deap>=1.3.3  # For MOEA
    - gym>=0.26.0  # For RL environment